import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Header from "../components/Header"
import Features from "../components/Features"
import Content from "../components/Content"
import Arrival from "../components/Arrival"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ChakraUI + Framer-Motion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Group 10.png" />
      </Head>
  <Navbar/>
  <br/>
  <Header/><br/>
  <Features/><br/>
  <Content/><br/>
  <Arrival/>
       
    </>
  )
}
